name: Build and Validate

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

jobs:
    validate:
        runs-on: ubuntu-latest
        environment: Production

        permissions:
            contents: read

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '24'
                    cache: 'npm'

            -   name: Install dependencies
                run: npm ci

            -   name: Generate Prisma Client
                run: npx prisma generate

            -   name: Typecheck
                run: npm run typecheck

            -   name: Build Next.js
                run: npm run build